var loadVosklet = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var k=moduleArg,ba,ca,da=new Promise((a,b)=>{ba=a;ca=b}),p="em-ww"==globalThis.name,ea="object"==typeof window,fa="undefined"!=typeof WorkerGlobalScope;
if(ea){var q=[],ha=["status","partialResult","result"];let a=caches.open("Vosklet"),b=URL.createObjectURL(new Blob(["(",(()=>{registerProcessor("VoskletTransferer",class extends AudioWorkletProcessor{constructor(e){super();this.ra=0;this.ya=e.processorOptions[0];this.va=new Float32Array(this.ya)}process(e){e[0][0]&&(this.va.set(e[0][0],this.ra),this.ra+=128,this.ra>=this.ya&&(this.ra=0,this.port.postMessage(this.va,[this.va.buffer]),this.va=new Float32Array(this.ya)));return!0}})}).toString(),")()"],
{type:"text/javascript"}));class c extends EventTarget{constructor(){super();q.push(this)}delete(){this.fa.delete()}static async pa(e,f,g,h){let l=new c,n=new Promise((t,w)=>{l.addEventListener("status",v=>{v.detail?w(v.detail):(h&&(l.findWord=z=>l.fa.findWord(z)),t(l))},{once:!0})}),m=await caches.open("Vosklet"),r=(await m.keys(f,{ignoreSearch:!0}))[0];if("undefined"==typeof r||r.url.split("?")[1]!=g){e=await fetch(e,{cache:"no-store"});if(!e.ok)throw"Unable to fetch model, status: "+e.status;e=
new Response(e.body.pipeThrough(new DecompressionStream("gzip")));await m.put(f+"?"+g,e.clone())}else e=await m.match(r);f=await e.arrayBuffer();g=u(f.byteLength);(x(),y).set(new Uint8Array(f),g);l.fa=new k.CommonModel(q.length-1,h,g,f.byteLength);return n}}class d extends EventTarget{constructor(){super();this.acceptWaveform=e=>{let f=u(4*e.length);(x(),ia).set(e,f/4);this.fa.acceptWaveform(f,e.length)};q.push(this);return new Proxy(this,{get(e,f){if(void 0!=e[f]||void 0!=e.fa[f]){var g=e[f];if(g)return g.bind?
g.bind(e):g;g=e.fa[f];return g.bind?g.bind(e.fa):g}}})}async delete(e=!1){let f=new Promise(g=>this.addEventListener("status",()=>{this.fa.delete();g()},{once:!0}));this.fa.safeDelete(e);return f}static async pa(e,f,g,h,l){let n=new d,m=new Promise((r,t)=>{n.addEventListener("status",w=>{w.detail?t(w.detail):r(n)},{once:!0})});switch(g){case 1:n.fa=new k.Recognizer(q.length-1,f,e);break;case 2:n.fa=new k.Recognizer(q.length-1,f,e,l);break;default:n.fa=new k.Recognizer(q.length-1,f,e,h,0)}return m}}
k={getModelCache:()=>a,cleanUp:async()=>{for(let e of q)await e.delete();URL.revokeObjectURL(b)},createTransferer:async(e,f)=>{await e.audioWorklet.addModule(b);return new AudioWorkletNode(e,"VoskletTransferer",{channelCountMode:"explicit",numberOfInputs:1,numberOfOutputs:0,channelCount:1,processorOptions:[f]})},createModel:(e,f,g)=>c.pa(e,f,g,!0),createSpkModel:(e,f,g)=>c.pa(e,f,g,!1),createRecognizer:(e,f)=>d.pa(e.fa,f,1),createRecognizerWithGrm:(e,f,g)=>d.pa(e.fa,f,3,g,null),createRecognizerWithSpkModel:(e,
f,g)=>d.pa(e.fa,f,2,null,g.fa)}}fa&&(_scriptName=self.location.href);var ja="",ka,la;if(ea||fa){try{ja=(new URL(".",_scriptName)).href}catch{}fa&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ka=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ma=console.log.bind(console),A=console.error.bind(console),B,na,oa=!1,C,y,D,F,G,H,ia,pa,qa,ra;
function x(){B.buffer!=C.buffer&&sa()}var ta,ua;p&&(onmessage=a=>{onmessage=null;ua=a=a.data;B=a.Ra;sa();ta(a.Da);a.Da=a.Ua=0});function sa(){var a=B.buffer;C=new Int8Array(a);D=new Int16Array(a);y=new Uint8Array(a);F=new Uint16Array(a);G=new Int32Array(a);H=new Uint32Array(a);ia=new Float32Array(a);ra=new Float64Array(a);pa=new BigInt64Array(a);qa=new BigUint64Array(a)}
function va(){p?(wa(ua.Pa,ua.Qa),xa(),removeEventListener("message",ya),za=za.forEach(Aa),addEventListener("message",Aa)):I.V()}var J=0,K=null;function Ba(a){a="Aborted("+a+")";A(a);oa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}var Ca;async function Da(a){try{var b=await ka(a);return new Uint8Array(b)}catch{}if(la)a=la(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ea(a,b){try{var c=await Da(a);return await WebAssembly.instantiate(c,b)}catch(d){A(`failed to asynchronously prepare wasm: ${d}`),Ba(d)}}async function Fa(a){var b=Ca;if("function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){A(`wasm streaming compile failed: ${d}`),A("falling back to ArrayBuffer instantiation")}return Ea(b,a)}
function Ia(){Ja={b:Ka,c:La,L:Ma,q:Na,P:Oa,o:Pa,i:Qa,f:Ra,N:Sa,G:Ta,j:Ua,p:Va,M:Wa,h:Xa,d:Ya,O:Za,m:$a,Q:ab,E:bb,s:cb,t:db,H:eb,A:fb,y:gb,z:hb,w:ib,u:jb,B:kb,x:lb,v:mb,D:nb,R:ob,T:pb,S:qb,e:rb,k:sb,l:ub,C:vb,I:wb,J:xb,K:yb,n:zb,g:Ab,a:B,r:Bb,F:Cb,U:Db};return{a:Ja}}class Eb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var za=[],Bb=a=>{throw new Eb(a);},zb=a=>{throw new Eb(a);},Fb=a=>{if(!oa)try{a()}catch(b){if(!(b instanceof Eb||"unwind"==b))throw b;}},Gb=[],Hb,Ib=a=>{var b=Gb[a];b||(Gb[a]=b=Hb.get(a));return b},Aa=a=>{let b=a.data,c=b._wsc;c&&Fb(()=>Ib(c)(...b.x))},ya=a=>{za.push(a)},Jb=new TextDecoder,L=(a,b)=>{if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&(x(),y)[c];)++c;return Jb.decode((x(),y).slice(a,c))},Ka=(a,b,c,d)=>Ba(`Assertion failed: ${L(a)}, at: `+[b?L(b):"unknown filename",c,d?L(d):"unknown function"]);
class Kb{constructor(a){this.da=a-24}}var Lb=0,Mb=0,La=(a,b,c)=>{var d=new Kb(a);(x(),H)[d.da+16>>2]=0;(x(),H)[d.da+4>>2]=b;(x(),H)[d.da+8>>2]=c;Lb=a;Mb++;throw Lb;},Ma=()=>Ba(""),Nb,M=a=>{for(var b="";(x(),y)[a];)b+=Nb[(x(),y)[a++]];return b},N={},O={},Ob={},P=class extends Error{constructor(a){super(a);this.name="BindingError"}},Pb=a=>{throw new P(a);};
function Qb(a,b,c={}){var d=b.name;if(!a)throw new P(`type "${d}" must have a positive integer typeid pointer`);if(O.hasOwnProperty(a)){if(c.Ja)return;throw new P(`Cannot register type '${d}' twice`);}O[a]=b;delete Ob[a];N.hasOwnProperty(a)&&(b=N[a],delete N[a],b.forEach(e=>e()))}function Q(a,b,c={}){return Qb(a,b,c)}
var Rb=(a,b,c)=>{switch(b){case 1:return c?d=>(x(),C)[d]:d=>(x(),y)[d];case 2:return c?d=>(x(),D)[d>>1]:d=>(x(),F)[d>>1];case 4:return c?d=>(x(),G)[d>>2]:d=>(x(),H)[d>>2];case 8:return c?d=>(x(),pa)[d>>3]:d=>(x(),qa)[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Na=(a,b,c,d,e)=>{b=M(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}Q(a,{name:b,fromWireType:f,toWireType:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},la:R,readValueFromPointer:Rb(b,
c,!d),ja:null})},R=8,Oa=(a,b,c,d)=>{b=M(b);Q(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},la:R,readValueFromPointer:function(e){return this.fromWireType((x(),y)[e])},ja:null})},Sb=a=>{throw new P(a.ba.ea.ca.name+" instance already deleted");},Tb=!1,Ub=()=>{},S=a=>{if("undefined"===typeof FinalizationRegistry)return S=b=>b,a;Tb=new FinalizationRegistry(b=>{b=b.ba;--b.count.value;0===b.count.value&&(b.ha?b.ka.ma(b.ha):b.ea.ca.ma(b.da))});S=b=>{var c=b.ba;c.ha&&
Tb.register(b,{ba:c},b);return b};Ub=b=>{Tb.unregister(b)};return S(a)},Vb=[];function Wb(){}
var Xb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Yb={},Zb=(a,b,c)=>{if(void 0===a[b].ga){var d=a[b];a[b]=function(...e){if(!a[b].ga.hasOwnProperty(e.length))throw new P(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ga})!`);return a[b].ga[e.length].apply(this,e)};a[b].ga=[];a[b].ga[d.qa]=d}},$b=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].ga&&void 0!==k[a].ga[c])throw new P(`Cannot register public name '${a}' twice`);Zb(k,
a,a);if(k[a].ga.hasOwnProperty(c))throw new P(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);k[a].ga[c]=b}else k[a]=b,k[a].qa=c},ac=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function bc(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.oa=c;this.ma=d;this.ia=e;this.Ha=f;this.ua=g;this.Fa=h;this.La=[]}
var cc=(a,b,c)=>{for(;b!==c;){if(!b.ua)throw new P(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ua(a);b=b.ia}return a},dc=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function ec(a,b){if(null===b){if(this.za)throw new P(`null is not a valid ${this.name}`);return 0}if(!b.ba)throw new P(`Cannot pass "${dc(b)}" as a ${this.name}`);if(!b.ba.da)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);return cc(b.ba.da,b.ba.ea.ca,this.ca)}
function fc(a,b){if(null===b){if(this.za)throw new P(`null is not a valid ${this.name}`);if(this.xa){var c=this.Ma();null!==a&&a.push(this.ma,c);return c}return 0}if(!b||!b.ba)throw new P(`Cannot pass "${dc(b)}" as a ${this.name}`);if(!b.ba.da)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.wa&&b.ba.ea.wa)throw new P(`Cannot convert argument of type ${b.ba.ka?b.ba.ka.name:b.ba.ea.name} to parameter type ${this.name}`);c=cc(b.ba.da,b.ba.ea.ca,this.ca);if(this.xa){if(void 0===
b.ba.ha)throw new P("Passing raw pointer to smart pointer is illegal");switch(this.Oa){case 0:if(b.ba.ka===this)c=b.ba.ha;else throw new P(`Cannot convert argument of type ${b.ba.ka?b.ba.ka.name:b.ba.ea.name} to parameter type ${this.name}`);break;case 1:c=b.ba.ha;break;case 2:if(b.ba.ka===this)c=b.ba.ha;else{var d=b.clone();c=this.Na(c,gc(()=>d["delete"]()));null!==a&&a.push(this.ma,c)}break;default:throw new P("Unsupporting sharing policy");}}return c}
function hc(a,b){if(null===b){if(this.za)throw new P(`null is not a valid ${this.name}`);return 0}if(!b.ba)throw new P(`Cannot pass "${dc(b)}" as a ${this.name}`);if(!b.ba.da)throw new P(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.ba.ea.wa)throw new P(`Cannot convert argument of type ${b.ba.ea.name} to parameter type ${this.name}`);return cc(b.ba.da,b.ba.ea.ca,this.ca)}function ic(a){return this.fromWireType((x(),H)[a>>2])}
var jc=(a,b,c)=>{if(b===c)return a;if(void 0===c.ia)return null;a=jc(a,b,c.ia);return null===a?null:c.Fa(a)},kc={},lc=(a,b)=>{if(void 0===b)throw new P("ptr should not be undefined");for(;a.ia;)b=a.ua(b),a=a.ia;return kc[b]},mc=class extends Error{constructor(a){super(a);this.name="InternalError"}},nc=(a,b)=>{if(!b.ea||!b.da)throw new mc("makeClassHandle requires ptr and ptrType");if(!!b.ka!==!!b.ha)throw new mc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return S(Object.create(a,
{ba:{value:b,writable:!0}}))};function oc(a,b,c,d,e,f,g,h,l,n,m){this.name=a;this.ca=b;this.za=c;this.wa=d;this.xa=e;this.Ka=f;this.Oa=g;this.Ca=h;this.Ma=l;this.Na=n;this.ma=m;e||void 0!==b.ia?this.toWireType=fc:(this.toWireType=d?ec:hc,this.ja=null)}
var pc=(a,b,c)=>{if(!k.hasOwnProperty(a))throw new mc("Replacing nonexistent public symbol");void 0!==k[a].ga&&void 0!==c?k[a].ga[c]=b:(k[a]=b,k[a].qa=c)},T=(a,b)=>{a=M(a);var c=Ib(b);if("function"!=typeof c)throw new P(`unknown function pointer with signature ${a}: ${b}`);return c};class qc extends Error{}
var sc=a=>{a=rc(a);var b=M(a);U(a);return b},tc=(a,b)=>{function c(f){e[f]||O[f]||(Ob[f]?Ob[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new qc(`${a}: `+d.map(sc).join([", "]));},V=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new mc("Mismatched type converter count");for(var l=0;l<a.length;++l)Q(a[l],h[l])}a.forEach(h=>Ob[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,l)=>{O.hasOwnProperty(h)?e[l]=O[h]:(f.push(h),N.hasOwnProperty(h)||(N[h]=[]),N[h].push(()=>
{e[l]=O[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},Pa=(a,b,c,d,e,f,g,h,l,n,m,r,t)=>{m=M(m);f=T(e,f);h&&=T(g,h);n&&=T(l,n);t=T(r,t);var w=ac(m);$b(w,function(){tc(`Cannot construct ${m} due to unbound types`,[d])});V([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var z=v.ca;var Z=z.oa}else Z=Wb.prototype;v=Xb(m,function(...Ga){if(Object.getPrototypeOf(this)!==Ha)throw new P(`Use 'new' to construct ${m}`);if(void 0===E.na)throw new P(`${m} has no accessible constructor`);var tb=E.na[Ga.length];if(void 0===
tb)throw new P(`Tried to invoke ctor of ${m} with invalid number of parameters (${Ga.length}) - expected (${Object.keys(E.na).toString()}) parameters instead!`);return tb.apply(this,Ga)});var Ha=Object.create(Z,{constructor:{value:v}});v.prototype=Ha;var E=new bc(m,v,Ha,t,z,f,h,n);if(E.ia){var aa;(aa=E.ia).Aa??(aa.Aa=[]);E.ia.Aa.push(E)}z=new oc(m,E,!0,!1,!1);aa=new oc(m+"*",E,!1,!1,!1);Z=new oc(m+" const*",E,!1,!0,!1);Yb[a]={pointerType:aa,Ea:Z};pc(w,v);return[z,aa,Z]})},uc=(a,b)=>{for(var c=[],
d=0;d<a;d++)c.push((x(),H)[b+4*d>>2]);return c},vc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function wc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ja)return!0;return!1}
function xc(a,b,c,d,e,f){var g=b.length;if(2>g)throw new P("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=wc(b);c="void"!==b[0].name;d=[a,Pb,d,e,vc,b[0],b[1]];for(e=0;e<g-2;++e)d.push(b[e+2]);if(!l)for(e=h?1:2;e<b.length;++e)null!==b[e].ja&&d.push(b[e].ja);l=wc(b);e=b.length-2;var n=[],m=["fn"];h&&m.push("thisWired");for(g=0;g<e;++g)n.push(`arg${g}`),m.push(`arg${g}Wired`);n=n.join(",");m=m.join(",");n=`return function (${n}) {\n`;l&&
(n+="var destructors = [];\n");var r=l?"destructors":"null",t="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");h&&(n+=`var thisWired = classParam['toWireType'](${r}, this);\n`);for(g=0;g<e;++g)n+=`var arg${g}Wired = argType${g}['toWireType'](${r}, arg${g});\n`,t.push(`argType${g}`);n+=(c||f?"var rv = ":"")+`invoker(${m});\n`;if(l)n+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].ja&&(n+=`${f}_dtor(${f});\n`,
t.push(`${f}_dtor`));c&&(n+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [w,v]=[t,n+"}\n"];b=(new Function(...w,v))(...d);return Xb(a,b)}
for(var Qa=(a,b,c,d,e,f)=>{var g=uc(b,c);e=T(d,e);V([],[a],h=>{h=h[0];var l=`constructor ${h.name}`;void 0===h.ca.na&&(h.ca.na=[]);if(void 0!==h.ca.na[b-1])throw new P(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.ca.na[b-1]=()=>{tc(`Cannot construct ${h.name} due to unbound types`,g)};V([],g,n=>{n.splice(1,0,null);h.ca.na[b-1]=xc(l,n,null,
e,f);return[]});return[]})},yc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Ra=(a,b,c,d,e,f,g,h,l)=>{var n=uc(c,d);b=M(b);b=yc(b);f=T(e,f);V([],[a],m=>{function r(){tc(`Cannot call ${t} due to unbound types`,n)}m=m[0];var t=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.ca.La.push(b);var w=m.ca.oa,v=w[b];void 0===v||void 0===v.ga&&v.className!==m.name&&v.qa===c-2?(r.qa=c-2,r.className=m.name,w[b]=r):(Zb(w,b,t),w[b].ga[c-2]=r);V([],n,z=>{z=xc(t,z,m,f,g,l);
void 0===w[b].ga?(z.qa=c-2,w[b]=z):w[b].ga[c-2]=z;return[]});return[]})},zc=[],W=[0,1,,1,null,1,!0,1,!1,1],gc=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=zc.pop()||W.length;W[b]=a;W[b+1]=1;return b}},Ac={name:"emscripten::val",fromWireType:a=>{if(!a)throw new P(`Cannot use deleted val. handle = ${a}`);var b=W[a];9<a&&0===--W[a+1]&&(W[a]=void 0,zc.push(a));return b},toWireType:(a,b)=>gc(b),la:R,readValueFromPointer:ic,ja:null},Sa=a=>Q(a,Ac),
Bc=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.fromWireType((x(),C)[d])}:function(d){return this.fromWireType((x(),y)[d])};case 2:return c?function(d){return this.fromWireType((x(),D)[d>>1])}:function(d){return this.fromWireType((x(),F)[d>>1])};case 4:return c?function(d){return this.fromWireType((x(),G)[d>>2])}:function(d){return this.fromWireType((x(),H)[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ta=(a,b,c,d)=>{function e(){}b=M(b);e.values={};Q(a,
{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:(f,g)=>g.value,la:R,readValueFromPointer:Bc(b,c,d),ja:null});$b(b,e)},Cc=a=>{var b=O[a];if(void 0===b)throw a=`${"enum"} has unknown type ${sc(a)}`,new P(a);return b},Ua=(a,b,c)=>{var d=Cc(a);b=M(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Xb(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d},Dc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType((x(),
ia)[c>>2])};case 8:return function(c){return this.fromWireType((x(),ra)[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Va=(a,b,c)=>{b=M(b);Q(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,la:R,readValueFromPointer:Dc(b,c),ja:null})},Wa=(a,b,c,d,e,f,g)=>{var h=uc(b,c);a=M(a);a=yc(a);e=T(d,e);$b(a,function(){tc(`Cannot call ${a} due to unbound types`,h)},b-1);V([],h,l=>{pc(a,xc(a,[l[0],null].concat(l.slice(1)),null,e,f,g),b-1);return[]})},Xa=(a,b,c,d,e)=>{b=M(b);let f=h=>
h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}Q(a,{name:b,fromWireType:f,toWireType:(h,l)=>l,la:R,readValueFromPointer:Rb(b,c,0!==d),ja:null})},Ya=(a,b,c)=>{function d(f){var g=(x(),H)[f>>2];f=(x(),H)[f+4>>2];return new e((x(),C).buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=M(c);Q(a,{name:c,fromWireType:d,la:R,readValueFromPointer:d},{Ja:!0})},Ec=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=
0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},X=(a,b,c)=>Ec(a,(x(),y),b,c),Y=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,
++c):b+=3}return b},Za=(a,b)=>{b=M(b);Q(a,{name:b,fromWireType:function(c){for(var d=(x(),H)[c>>2],e=c+4,f,g=e,h=0;h<=d;++h){var l=e+h;if(h==d||0==(x(),y)[l])g=L(g,l-g),void 0===f?f=g:(f+=String.fromCharCode(0),f+=g),g=l+1}U(c);return f},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new P("Cannot pass non-string to std::string");var f=e?Y(d):d.length;var g=u(4+f+1),h=g+4;(x(),H)[g>>2]=
f;e?X(d,h,f+1):(x(),y).set(d,h);null!==c&&c.push(U,g);return g},la:R,readValueFromPointer:ic,ja(c){U(c)}})},Fc=new TextDecoder("utf-16le"),Gc=(a,b)=>{a>>=1;b=a+b/2;for(var c=a;!(c>=b)&&(x(),F)[c];)++c;return Fc.decode((x(),F).buffer instanceof ArrayBuffer?(x(),F).subarray(a,c):(x(),F).slice(a,c))},Hc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);(x(),D)[b>>1]=f;b+=2}(x(),D)[b>>1]=0;return b-d},Ic=a=>2*a.length,Jc=(a,b)=>
{for(var c=0,d="";!(c>=b/4);){var e=(x(),G)[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Kc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}(x(),G)[b>>2]=f;b+=4;if(b+4>c)break}(x(),G)[b>>2]=0;return b-d},Lc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=
d&&++c;b+=4}return b},$a=(a,b,c)=>{c=M(c);if(2===b){var d=Gc;var e=Hc;var f=Ic;var g=h=>(x(),F)[h>>1]}else 4===b&&(d=Jc,e=Kc,f=Lc,g=h=>(x(),H)[h>>2]);Q(a,{name:c,fromWireType:h=>{for(var l=(x(),H)[h>>2],n,m=h+4,r=0;r<=l;++r){var t=h+4+r*b;if(r==l||0==g(t))m=d(m,t-m),void 0===n?n=m:(n+=String.fromCharCode(0),n+=m),m=t+b}U(h);return n},toWireType:(h,l)=>{if("string"!=typeof l)throw new P(`Cannot pass non-string to C++ string type ${c}`);var n=f(l),m=u(4+n+b);(x(),H)[m>>2]=n/b;e(l,m+4,n+b);null!==h&&
h.push(U,m);return m},la:R,readValueFromPointer:ic,ja(h){U(h)}})},ab=(a,b)=>{b=M(b);Q(a,{Ta:!0,name:b,la:0,fromWireType:()=>{},toWireType:()=>{}})},Mc={},Nc=1,bb=(a,b)=>{let c;c=Mc[Nc]=new Worker(ja+"Vosklet.js",{name:"em-ww"});c.postMessage({Ya:Nc,Da:na,Ra:B,Pa:a,Qa:b});c.onmessage=Aa;return Nc++},cb=()=>{},Oc={},ub=()=>performance.now(),db=(a,b)=>{Oc[a]&&(clearTimeout(Oc[a].id),delete Oc[a]);if(!b)return 0;var c=setTimeout(()=>{delete Oc[a];Fb(()=>Pc(a,performance.now()))},b);Oc[a]={id:c,Xa:b};
return 0},eb=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);(x(),H)[a>>2]=60*g;(x(),G)[b>>2]=Number(f!=e);b=h=>{var l=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(X(a,c,17),X(b,d,17)):(X(a,d,17),X(b,c,17))},fb=(a,b)=>(x(),y).set(Qc[a].Ga,b),Rc=[],gb=()=>Rc.length,Qc=[],hb=()=>Qc.length,ib=(a,b)=>{a=Rc[a].Sa;X(a,b,Y(a)+
1)},jb=a=>Qc[a].mode,kb=a=>Qc[a].Ga.length,lb=(a,b)=>{a=Rc[a].Va;X(a,b,Y(a)+1)},mb=(a,b)=>{a=Qc[a].Wa;X(a,b,Y(a)+1)},Sc=[],nb=()=>{a:{if(!Sc.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(Y(a)+1);a=Ec(a,b,0,b.length);b.length=a;Sc=b}b=Sc.shift()}return"number"===typeof b?b:-1},ob=a=>{console.error(L(a))},pb=a=>{console.log(L(a))},qb=a=>{console.warn(L(a))},rb=()=>Date.now(),sb=a=>A(L(a)),
vb=a=>ma(L(a)),wb=a=>{var b=(x(),y).length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-B.buffer.byteLength+65535)/65536|0;try{B.grow(d);sa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Tc={},Vc=()=>{if(!Uc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||
"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in Tc)void 0===Tc[b]?delete a[b]:a[b]=Tc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Uc=c}return Uc},Uc,xb=(a,b)=>{var c=0,d=0,e;for(e of Vc()){var f=b+c;(x(),H)[a+d>>2]=f;c+=X(e,f,Infinity)+1;d+=4}return 0},yb=(a,b)=>{var c=Vc();(x(),H)[a>>2]=c.length;a=0;for(var d of c)a+=Y(d)+1;(x(),H)[b>>2]=a;return 0},Wc=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),Xc=a=>{(Xc=Wc())(a)},Cb=(a,b)=>{Xc((x(),y).subarray(a,a+b));return 0},
Yc=Array(256),Zc=0;256>Zc;++Zc)Yc[Zc]=String.fromCharCode(Zc);Nb=Yc;
(()=>{let a=Wb.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Wb&&c instanceof Wb))return!1;var d=this.ba.ea.ca,e=this.ba.da;c.ba=c.ba;var f=c.ba.ea.ca;for(c=c.ba.da;d.ia;)e=d.ua(e),d=d.ia;for(;f.ia;)c=f.ua(c),f=f.ia;return d===f&&e===c},clone:function(){this.ba.da||Sb(this);if(this.ba.ta)return this.ba.count.value+=1,this;var c=S,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.ba;c=c(e.call(d,f,{ba:{value:{count:g.count,sa:g.sa,ta:g.ta,da:g.da,ea:g.ea,ha:g.ha,ka:g.ka}}}));
c.ba.count.value+=1;c.ba.sa=!1;return c},["delete"](){this.ba.da||Sb(this);if(this.ba.sa&&!this.ba.ta)throw new P("Object already scheduled for deletion");Ub(this);var c=this.ba;--c.count.value;0===c.count.value&&(c.ha?c.ka.ma(c.ha):c.ea.ca.ma(c.da));this.ba.ta||(this.ba.ha=void 0,this.ba.da=void 0)},isDeleted:function(){return!this.ba.da},deleteLater:function(){this.ba.da||Sb(this);if(this.ba.sa&&!this.ba.ta)throw new P("Object already scheduled for deletion");Vb.push(this);this.ba.sa=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(oc.prototype,{Ia(a){this.Ca&&(a=this.Ca(a));return a},Ba(a){this.ma?.(a)},la:R,readValueFromPointer:ic,fromWireType:function(a){function b(){return this.xa?nc(this.ca.oa,{ea:this.Ka,da:c,ka:this,ha:a}):nc(this.ca.oa,{ea:this,da:a})}var c=this.Ia(a);if(!c)return this.Ba(a),null;var d=lc(this.ca,c);if(void 0!==d){if(0===d.ba.count.value)return d.ba.da=c,d.ba.ha=a,d.clone();d=d.clone();this.Ba(a);return d}d=this.ca.Ha(c);d=Yb[d];if(!d)return b.call(this);d=this.wa?d.Ea:d.pointerType;var e=
jc(c,this.ca,d.ca);return null===e?b.call(this):this.xa?nc(d.ca.oa,{ea:d,da:e,ka:this,ha:a}):nc(d.ca.oa,{ea:d,da:e})}});p&&(Mc[0]=globalThis,addEventListener("message",ya));p||(k.wasmMemory?B=k.wasmMemory:B=new WebAssembly.Memory({initial:5040,maximum:32768,shared:!0}),sa());function Ab(a,b,c){ea?q[a].dispatchEvent(new CustomEvent(ha[b],{detail:0==c?null:L(c)})):self.postMessage([a,b,c])}function Db(a,b){for(let c of Object.values(Mc))c.postMessage({_wsc:a,x:[b]}),c.onmessage=d=>Ab(...d.data)}
var Ja,I=await (async function(){function a(d,e){I=d.exports;Hb=I._;na=e;J--;0==J&&K&&(d=K,K=null,d());return I}J++;var b=Ia();if(k.instantiateWasm)return new Promise(d=>{k.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(p)return new Promise(d=>{ta=e=>{var f=new WebAssembly.Instance(e,Ia());d(a(f,e))}});Ca??=ja+"Vosklet.wasm";try{var c=await Fa(b);return a(c.instance,c.module)}catch(d){return ca(d),Promise.reject(d)}}()),U=a=>(U=I.W)(a),u=a=>(u=I.X)(a),rc=a=>(rc=I.Y)(a),xa=()=>(xa=I.Z)(),Pc=
(a,b)=>(Pc=I.$)(a,b),wa=(a,b)=>(wa=I.aa)(a,b);function $c(){0<J?K=$c:p?(ba(k),va()):0<J?K=$c:(k.calledRun=!0,oa||(va(),ba(k)))}$c();moduleRtn=da;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = loadVosklet;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = loadVosklet;
} else if (typeof define === 'function' && define['amd'])
  define([], () => loadVosklet);
var isWW = globalThis.self?.name == 'em-ww';
// When running as a wasm worker, construct a new instance on startup
isWW && loadVosklet();
