
var loadVosklet = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

function h(){p.buffer!=q.buffer&&r();return q}function t(){p.buffer!=q.buffer&&r();return aa}function ba(){p.buffer!=q.buffer&&r();return ca}function da(){p.buffer!=q.buffer&&r();return ha}function u(){p.buffer!=q.buffer&&r();return ia}function z(){p.buffer!=q.buffer&&r();return ja}function ka(){p.buffer!=q.buffer&&r();return la}
var A=moduleArg,ma,na,oa=new Promise((a,b)=>{ma=a;na=b}),pa="object"==typeof window,qa="function"==typeof importScripts,ra="object"==typeof process&&"object"==typeof process.Oa&&"string"==typeof process.Oa.node,sa=A.$ww;
let B=[],ta=["status","partialResult","result"],ua=URL.createObjectURL(new Blob(["(",(()=>{let a=new TextDecoder,b=new TextEncoder;onmessage=async c=>{c=c.data;var d=c.Na.split("/"),e=await navigator.storage.getDirectory();for(var f of d)e=await e.getDirectoryHandle(f,{create:!0});d=await e.getFileHandle("id",{create:!0});f=await e.getFileHandle("model.tgz",{create:!0});e=await d.createSyncAccessHandle();d=await f.createSyncAccessHandle();f=new ArrayBuffer(e.getSize());e.read(f);let g;if(a.decode(f)==
c.id)g=new ArrayBuffer(d.getSize()),d.read(g),c=await (new Response((new Response(g)).body.pipeThrough(new DecompressionStream("gzip")))).arrayBuffer();else{f=await fetch(c.url);if(!f.ok){postMessage("Unable to download model");return}f=f.body.tee();g=await (new Response(f[0])).arrayBuffer();d.write(g,{at:0});d.truncate(g.byteLength);c=b.encode(c.id);e.write(c,{at:0});e.truncate(c.length);c=await (new Response(f[1].pipeThrough(new DecompressionStream("gzip")))).arrayBuffer()}e.close();d.close();self.postMessage(c,
[c])}}).toString(),")()"],{type:"text/javascript"})),va=new Worker(ua),wa=URL.createObjectURL(new Blob(["(",(()=>{registerProcessor("VoskletTransferer",class extends AudioWorkletProcessor{constructor(a){super();this.count=0;this.sa=a.processorOptions.sa;this.buffer=new Float32Array(128*this.sa)}process(a){if(!a[0][0])return!0;this.buffer.set(a[0][0],128*this.count++);this.count>=this.sa&&(this.count=0,this.port.postMessage(this.buffer,[this.buffer.buffer]),this.buffer=new Float32Array(128*this.sa));
return!0}})}).toString(),")()"],{type:"text/javascript"}));A.cleanUp=async()=>{for(let a of B)await a.delete();URL.revokeObjectURL(wa);URL.revokeObjectURL(ua);va.terminate()};A.createTransferer=async(a,b)=>{await a.audioWorklet.addModule(wa);return new AudioWorkletNode(a,"VoskletTransferer",{channelCountMode:"explicit",numberOfInputs:1,numberOfOutputs:0,channelCount:1,processorOptions:{sa:b/128}})};
async function xa(a,b,c,d){let e=new ya,f=new Promise((g,k)=>{e.addEventListener("status",l=>{l.detail?k(l.detail):(d&&(e.findWord=m=>e.ha.findWord(m)),g(e))},{once:!0})});va.addEventListener("message",g=>{g=g.data;let k=C(g.byteLength);t().set(new Uint8Array(g),k);e.ha=new A.CommonModel(B.length-1,d,"/"+b,c,k,g.byteLength)},{once:!0});va.postMessage({url:a,Na:b,id:c});return f}class ya extends EventTarget{constructor(){super();B.push(this)}delete(){this.ha.delete()}}
A.createModel=async(a,b,c)=>xa(a,b,c,!0);A.createSpkModel=async(a,b,c)=>xa(a,b,c,!1);async function za(a,b,c,d,e){let f=new Aa,g=new Promise((k,l)=>{f.addEventListener("status",m=>{m.detail?l(m.detail):k(f)},{once:!0})});switch(c){case 1:f.ha=new A.Recognizer(B.length-1,b,a);break;case 2:f.ha=new A.Recognizer(B.length-1,b,a,e);break;default:f.ha=new A.Recognizer(B.length-1,b,a,d,0)}return g}
class Aa extends EventTarget{constructor(){super();this.acceptWaveform=a=>{let b=C(4*a.length);ka().set(a,b/4);this.ha.acceptWaveform(b,a.length)};B.push(this);return new Proxy(this,{get(a,b){if(void 0!=a[b]||void 0!=a.ha[b]){var c=a[b];if(c)return c.bind?c.bind(a):c;c=a.ha[b];return c.bind?c.bind(a.ha):c}}})}async delete(a=!1){let b=new Promise(c=>this.addEventListener("status",()=>{this.ha.delete();c()},{once:!0}));this.ha.Ua(a);return b}}A.createRecognizer=(a,b)=>za(a.ha,b,1);
A.createRecognizerWithSpkModel=(a,b,c)=>za(a.ha,b,2,null,c.ha);A.createRecognizerWithGrm=(a,b,c)=>za(a.ha,b,3,c,null);var Ba=Object.assign({},A),Ca="./this.program",D="",Da,Ea;
if(pa||qa)qa?D=self.location.href:"undefined"!=typeof document&&document.currentScript&&(D=document.currentScript.src),_scriptName&&(D=_scriptName),D.startsWith("blob:")?D="":D=D.substr(0,D.replace(/[?#].*/,"").lastIndexOf("/")+1),qa&&(Ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),Da=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));
var Fa=A.print||console.log.bind(console),G=A.printErr||console.error.bind(console);Object.assign(A,Ba);Ba=null;A.thisProgram&&(Ca=A.thisProgram);var Ga=A.wasmBinary,p,Ha,Ia=!1,Ja,q,aa,ca,ha,ia,ja,la,Ka,La,Ma;
function r(){var a=p.buffer;A.HEAP8=q=new Int8Array(a);A.HEAP16=ca=new Int16Array(a);A.HEAPU8=aa=new Uint8Array(a);A.HEAPU16=ha=new Uint16Array(a);A.HEAP32=ia=new Int32Array(a);A.HEAPU32=ja=new Uint32Array(a);A.HEAPF32=la=new Float32Array(a);A.HEAPF64=Ma=new Float64Array(a);A.HEAP64=Ka=new BigInt64Array(a);A.HEAPU64=La=new BigUint64Array(a)}
if(A.wasmMemory)p=A.wasmMemory;else if(p=new WebAssembly.Memory({initial:(A.INITIAL_MEMORY||330301440)/65536,maximum:32768,shared:!0}),!(p.buffer instanceof SharedArrayBuffer))throw G("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),ra&&G("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");r();var Na=[],Oa=[],Pa=[];function Qa(){sa?(Ra(A.sb,A.sz),removeEventListener("message",Sa),Ta=Ta.forEach(Ua),addEventListener("message",Ua)):Va(Oa)}function Wa(){var a=A.preRun.shift();Na.unshift(a)}var H=0,Xa=null,I=null;function Ya(a){A.onAbort?.(a);a="Aborted("+a+")";G(a);Ia=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");na(a);throw a;}var Za=a=>a.startsWith("data:application/octet-stream;base64,"),$a;
function ab(a){if(a==$a&&Ga)return new Uint8Array(Ga);if(Ea)return Ea(a);throw"both async and sync fetching of the wasm failed";}function bb(a){return Ga?Promise.resolve().then(()=>ab(a)):Da(a).then(b=>new Uint8Array(b),()=>ab(a))}function eb(a,b,c){return bb(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{G(`failed to asynchronously prepare wasm: ${d}`);Ya(d)})}
function fb(a,b){var c=$a;return Ga||"function"!=typeof WebAssembly.instantiateStreaming||Za(c)||"function"!=typeof fetch?eb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){G(`wasm streaming compile failed: ${e}`);G("falling back to ArrayBuffer instantiation");return eb(c,a,b)}))}function gb(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ta=[],hb=[],ib,jb=a=>{var b=hb[a];b||(a>=hb.length&&(hb.length=a+1),hb[a]=b=ib.get(a));return b},Ua=a=>{a=a.data;let b=a._wsc;b&&jb(b)(...a.x)},Sa=a=>{Ta.push(a)},Va=a=>{for(;0<a.length;)a.shift()(A)},kb=A.noExitRuntime||!0,lb=new TextDecoder,J=(a,b)=>{if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&t()[c];)++c;return lb.decode(t().slice(a,c))};class mb{constructor(a){this.fa=a-24}}
var nb=0,ob=0,pb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},qb,K=a=>{for(var b="";t()[a];)b+=qb[t()[a++]];return b},L={},M={},rb={},N,sb=a=>{throw new N(a);},O,Q=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new O("Mismatched type converter count");for(var l=0;l<a.length;++l)P(a[l],k[l])}a.forEach(k=>rb[k]=b);var e=Array(b.length),f=[],g=0;b.forEach((k,l)=>{M.hasOwnProperty(k)?e[l]=M[k]:(f.push(k),L.hasOwnProperty(k)||
(L[k]=[]),L[k].push(()=>{e[l]=M[k];++g;g===f.length&&d(e)}))});0===f.length&&d(e)};function tb(a,b,c={}){var d=b.name;if(!a)throw new N(`type "${d}" must have a positive integer typeid pointer`);if(M.hasOwnProperty(a)){if(c.Ha)return;throw new N(`Cannot register type '${d}' twice`);}M[a]=b;delete rb[a];L.hasOwnProperty(a)&&(b=L[a],delete L[a],b.forEach(e=>e()))}function P(a,b,c={}){return tb(a,b,c)}
var ub=(a,b,c)=>{switch(b){case 1:return c?d=>h()[d]:d=>t()[d];case 2:return c?d=>ba()[d>>1]:d=>da()[d>>1];case 4:return c?d=>u()[d>>2]:d=>z()[d>>2];case 8:return c?d=>Ka[d>>3]:d=>La[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},vb=a=>{throw new N(a.da.ga.ea.name+" instance already deleted");},wb=!1,xb=()=>{},yb=(a,b,c)=>{if(b===c)return a;if(void 0===c.ka)return null;a=yb(a,b,c.ka);return null===a?null:c.Da(a)},zb={},R=[],Ab=()=>{for(;R.length;){var a=R.pop();a.da.qa=
!1;a["delete"]()}},S,T={},Bb=(a,b)=>{if(void 0===b)throw new N("ptr should not be undefined");for(;a.ka;)b=a.ua(b),a=a.ka;return T[b]},Cb=(a,b)=>{if(!b.ga||!b.fa)throw new O("makeClassHandle requires ptr and ptrType");if(!!b.ma!==!!b.ia)throw new O("Both smartPtrType and smartPtr must be specified");b.count={value:1};return U(Object.create(a,{da:{value:b,writable:!0}}))},U=a=>{if("undefined"===typeof FinalizationRegistry)return U=b=>b,a;wb=new FinalizationRegistry(b=>{b=b.da;--b.count.value;0===b.count.value&&
(b.ia?b.ma.oa(b.ia):b.ga.ea.oa(b.fa))});U=b=>{var c=b.da;c.ia&&wb.register(b,{da:c},b);return b};xb=b=>{wb.unregister(b)};return U(a)};function Db(){}
var Eb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Fb=(a,b,c)=>{if(void 0===a[b].ja){var d=a[b];a[b]=function(...e){if(!a[b].ja.hasOwnProperty(e.length))throw new N(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ja})!`);return a[b].ja[e.length].apply(this,e)};a[b].ja=[];a[b].ja[d.va]=d}},Gb=(a,b,c)=>{if(A.hasOwnProperty(a)){if(void 0===c||void 0!==A[a].ja&&void 0!==A[a].ja[c])throw new N(`Cannot register public name '${a}' twice`);Fb(A,a,a);
if(A.hasOwnProperty(c))throw new N(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);A[a].ja[c]=b}else A[a]=b,void 0!==c&&(A[a].Ra=c)},Hb=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Ib(a,b,c,d,e,f,g,k){this.name=a;this.constructor=b;this.ra=c;this.oa=d;this.ka=e;this.Fa=f;this.ua=g;this.Da=k;this.Ja=[]}
var Jb=(a,b,c)=>{for(;b!==c;){if(!b.ua)throw new N(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ua(a);b=b.ka}return a};function Kb(a,b){if(null===b){if(this.ya)throw new N(`null is not a valid ${this.name}`);return 0}if(!b.da)throw new N(`Cannot pass "${pb(b)}" as a ${this.name}`);if(!b.da.fa)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);return Jb(b.da.fa,b.da.ga.ea,this.ea)}
function Lb(a,b){if(null===b){if(this.ya)throw new N(`null is not a valid ${this.name}`);if(this.xa){var c=this.Ka();null!==a&&a.push(this.oa,c);return c}return 0}if(!b||!b.da)throw new N(`Cannot pass "${pb(b)}" as a ${this.name}`);if(!b.da.fa)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.wa&&b.da.ga.wa)throw new N(`Cannot convert argument of type ${b.da.ma?b.da.ma.name:b.da.ga.name} to parameter type ${this.name}`);c=Jb(b.da.fa,b.da.ga.ea,this.ea);if(this.xa){if(void 0===
b.da.ia)throw new N("Passing raw pointer to smart pointer is illegal");switch(this.Ma){case 0:if(b.da.ma===this)c=b.da.ia;else throw new N(`Cannot convert argument of type ${b.da.ma?b.da.ma.name:b.da.ga.name} to parameter type ${this.name}`);break;case 1:c=b.da.ia;break;case 2:if(b.da.ma===this)c=b.da.ia;else{var d=b.clone();c=this.La(c,Mb(()=>d["delete"]()));null!==a&&a.push(this.oa,c)}break;default:throw new N("Unsupporting sharing policy");}}return c}
function Nb(a,b){if(null===b){if(this.ya)throw new N(`null is not a valid ${this.name}`);return 0}if(!b.da)throw new N(`Cannot pass "${pb(b)}" as a ${this.name}`);if(!b.da.fa)throw new N(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.da.ga.wa)throw new N(`Cannot convert argument of type ${b.da.ga.name} to parameter type ${this.name}`);return Jb(b.da.fa,b.da.ga.ea,this.ea)}function Ob(a){return this.fromWireType(z()[a>>2])}
function Pb(a,b,c,d,e,f,g,k,l,m,n){this.name=a;this.ea=b;this.ya=c;this.wa=d;this.xa=e;this.Ia=f;this.Ma=g;this.Ba=k;this.Ka=l;this.La=m;this.oa=n;e||void 0!==b.ka?this.toWireType=Lb:(this.toWireType=d?Kb:Nb,this.la=null)}
var Qb=(a,b,c)=>{if(!A.hasOwnProperty(a))throw new O("Replacing nonexistent public symbol");void 0!==A[a].ja&&void 0!==c?A[a].ja[c]=b:(A[a]=b,A[a].va=c)},V=(a,b)=>{a=K(a);var c=jb(b);if("function"!=typeof c)throw new N(`unknown function pointer with signature ${a}: ${b}`);return c},Rb,Tb=a=>{a=Sb(a);var b=K(a);W(a);return b},Ub=(a,b)=>{function c(f){e[f]||M[f]||(rb[f]?rb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Rb(`${a}: `+d.map(Tb).join([", "]));},Vb=(a,b)=>{for(var c=
[],d=0;d<a;d++)c.push(z()[b+4*d>>2]);return c},Wb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Xb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].la)return!0;return!1}function Zb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Eb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function $b(a,b,c,d,e,f){var g=b.length;if(2>g)throw new N("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,l=Xb(b);c="void"!==b[0].name;d=[a,sb,d,e,Wb,b[0],b[1]];for(e=0;e<g-2;++e)d.push(b[e+2]);if(!l)for(e=k?1:2;e<b.length;++e)null!==b[e].la&&d.push(b[e].la);l=Xb(b);e=b.length-2;var m=[],n=["fn"];k&&n.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),n.push(`arg${g}Wired`);m=m.join(",");n=n.join(",");m=`\n        return function (${m}) {\n        if (arguments.length !== ${e}) {\n          throwBindingError('function ' + humanName + ' called with ' + arguments.length + ' arguments, expected ${e}');\n        }`;
l&&(m+="var destructors = [];\n");var x=l?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");k&&(m+=`var thisWired = classParam['toWireType'](${x}, this);\n`);for(g=0;g<e;++g)m+=`var arg${g}Wired = argType${g}['toWireType'](${x}, arg${g});\n`,v.push(`argType${g}`);m+=(c||f?"var rv = ":"")+`invoker(${n});\n`;if(l)m+="runDestructors(destructors);\n";else for(g=k?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].la&&(m+=`${f}_dtor(${f});\n`,
v.push(`${f}_dtor`));c&&(m+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [y,w]=[v,m+"}\n"];y.push(w);b=Zb(y)(...d);return Eb(a,b)}
var ac=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},bc=[],X=[],Mb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=bc.pop()||X.length;X[b]=a;X[b+1]=1;return b}},cc={name:"emscripten::val",fromWireType:a=>{if(!a)throw new N("Cannot use deleted val. handle = "+a);var b=X[a];9<a&&0===--X[a+1]&&(X[a]=void 0,bc.push(a));return b},toWireType:(a,b)=>Mb(b),na:8,readValueFromPointer:Ob,la:null},dc=(a,b,c)=>{switch(b){case 1:return c?
function(d){return this.fromWireType(h()[d])}:function(d){return this.fromWireType(t()[d])};case 2:return c?function(d){return this.fromWireType(ba()[d>>1])}:function(d){return this.fromWireType(da()[d>>1])};case 4:return c?function(d){return this.fromWireType(u()[d>>2])}:function(d){return this.fromWireType(z()[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},ec=a=>{var b=M[a];if(void 0===b)throw a=`${"enum"} has unknown type ${Tb(a)}`,new N(a);return b},fc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ka()[c>>
2])};case 8:return function(c){var d=this.fromWireType;p.buffer!=q.buffer&&r();return d.call(this,Ma[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Y=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;
b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},gc=(a,b)=>{var c=17;Y(a,t(),b,c)},hc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ic=new TextDecoder("utf-16le"),jc=(a,b)=>{var c=a>>1;for(b=c+b/2;!(c>=b)&&da()[c];)++c;c<<=1;return ic.decode(t().slice(a,c))},kc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);
ba()[b>>1]=f;b+=2}ba()[b>>1]=0;return b-d},lc=a=>2*a.length,mc=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=u()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},nc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}u()[b>>2]=f;b+=4;if(b+4>c)break}u()[b>>2]=0;return b-d},oc=a=>{for(var b=
0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},pc={},qc=1,rc=URL.createObjectURL(new Blob(["onmessage=function(d){onmessage=null;d=d.data;d[`instantiateWasm`]=(i,r)=>{var n=new WebAssembly.Instance(d[`wasm`],i);return r(n,d[`wasm`]);};importScripts(d.js);loadVosklet(d);d.wasm=d.mem=d.js=0;}"],{type:"application/javascript"})),sc={},tc=a=>{if(!(a instanceof gb||"unwind"==a))throw a;},uc=0,vc=a=>{Ja=a;kb||0<uc||(A.onExit?.(a),Ia=!0);throw new gb(a);},wc=a=>{if(!Ia)try{if(a(),
!(kb||0<uc))try{Ja=a=Ja,vc(a)}catch(b){tc(b)}}catch(b){tc(b)}},xc;xc=()=>performance.now();
for(var yc=[],zc=[],Ac=[],Bc={},Dc=()=>{if(!Cc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:Ca||"./this.program"},b;for(b in Bc)void 0===Bc[b]?delete a[b]:a[b]=Bc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Cc=c}return Cc},Cc,Ec=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),
a);Ya("initRandomDevice")},Fc=a=>(Fc=Ec())(a),Gc=Array(256),Hc=0;256>Hc;++Hc)Gc[Hc]=String.fromCharCode(Hc);qb=Gc;N=A.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};O=A.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(Db.prototype,{isAliasOf:function(a){if(!(this instanceof Db&&a instanceof Db))return!1;var b=this.da.ga.ea,c=this.da.fa;a.da=a.da;var d=a.da.ga.ea;for(a=a.da.fa;b.ka;)c=b.ua(c),b=b.ka;for(;d.ka;)a=d.ua(a),d=d.ka;return b===d&&c===a},clone:function(){this.da.fa||vb(this);if(this.da.ta)return this.da.count.value+=1,this;var a=U,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.da;a=a(c.call(b,d,{da:{value:{count:e.count,qa:e.qa,ta:e.ta,fa:e.fa,ga:e.ga,ia:e.ia,ma:e.ma}}}));a.da.count.value+=
1;a.da.qa=!1;return a},["delete"](){this.da.fa||vb(this);if(this.da.qa&&!this.da.ta)throw new N("Object already scheduled for deletion");xb(this);var a=this.da;--a.count.value;0===a.count.value&&(a.ia?a.ma.oa(a.ia):a.ga.ea.oa(a.fa));this.da.ta||(this.da.ia=void 0,this.da.fa=void 0)},isDeleted:function(){return!this.da.fa},deleteLater:function(){this.da.fa||vb(this);if(this.da.qa&&!this.da.ta)throw new N("Object already scheduled for deletion");R.push(this);1===R.length&&S&&S(Ab);this.da.qa=!0;return this}});
A.getInheritedInstanceCount=()=>Object.keys(T).length;A.getLiveInheritedInstances=()=>{var a=[],b;for(b in T)T.hasOwnProperty(b)&&a.push(T[b]);return a};A.flushPendingDeletes=Ab;A.setDelayFunction=a=>{S=a;R.length&&S&&S(Ab)};
Object.assign(Pb.prototype,{Ga(a){this.Ba&&(a=this.Ba(a));return a},Aa(a){this.oa?.(a)},na:8,readValueFromPointer:Ob,fromWireType:function(a){function b(){return this.xa?Cb(this.ea.ra,{ga:this.Ia,fa:c,ma:this,ia:a}):Cb(this.ea.ra,{ga:this,fa:a})}var c=this.Ga(a);if(!c)return this.Aa(a),null;var d=Bb(this.ea,c);if(void 0!==d){if(0===d.da.count.value)return d.da.fa=c,d.da.ia=a,d.clone();d=d.clone();this.Aa(a);return d}d=this.ea.Fa(c);d=zb[d];if(!d)return b.call(this);d=this.wa?d.Ca:d.pointerType;var e=
yb(c,this.ea,d.ea);return null===e?b.call(this):this.xa?Cb(d.ea.ra,{ga:d,fa:e,ma:this,ia:a}):Cb(d.ea.ra,{ga:d,fa:e})}});Rb=A.UnboundTypeError=((a,b)=>{var c=Eb(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
X.push(0,1,void 0,1,null,1,!0,1,!1,1);A.count_emval_handles=()=>X.length/2-5-bc.length;sa&&(pc[0]=this,addEventListener("message",Sa));
var Jc={c:(a,b,c,d)=>{Ya(`Assertion failed: ${J(a)}, at: `+[b?J(b):"unknown filename",c,d?J(d):"unknown function"])},t:(a,b)=>jb(a)(b),d:(a,b,c)=>{var d=new mb(a);z()[d.fa+16>>2]=0;z()[d.fa+4>>2]=b;z()[d.fa+8>>2]=c;nb=a;ob++;throw nb;},P:()=>{Ya("")},q:(a,b,c)=>{b=K(b);P(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${pb(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},na:8,readValueFromPointer:ub(b,
c,-1==b.indexOf("u")),la:null})},S:(a,b,c,d)=>{b=K(b);P(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},na:8,readValueFromPointer:function(e){return this.fromWireType(t()[e])},la:null})},o:(a,b,c,d,e,f,g,k,l,m,n,x,v)=>{n=K(n);f=V(e,f);k&&=V(g,k);m&&=V(l,m);v=V(x,v);var y=Hb(n);Gb(y,function(){Ub(`Cannot construct ${n} due to unbound types`,[d])});Q([a,b,c],d?[d]:[],w=>{w=w[0];if(d){var E=w.ea;var ea=E.ra}else ea=Db.prototype;w=Eb(n,function(...cb){if(Object.getPrototypeOf(this)!==
db)throw new N("Use 'new' to construct "+n);if(void 0===F.pa)throw new N(n+" has no accessible constructor");var Yb=F.pa[cb.length];if(void 0===Yb)throw new N(`Tried to invoke ctor of ${n} with invalid number of parameters (${cb.length}) - expected (${Object.keys(F.pa).toString()}) parameters instead!`);return Yb.apply(this,cb)});var db=Object.create(ea,{constructor:{value:w}});w.prototype=db;var F=new Ib(n,w,db,v,E,f,k,m);if(F.ka){var fa;(fa=F.ka).za??(fa.za=[]);F.ka.za.push(F)}E=new Pb(n,F,!0,!1,
!1);fa=new Pb(n+"*",F,!1,!1,!1);ea=new Pb(n+" const*",F,!1,!0,!1);zb[a]={pointerType:fa,Ca:ea};Qb(y,w);return[E,fa,ea]})},j:(a,b,c,d,e,f)=>{var g=Vb(b,c);e=V(d,e);Q([],[a],k=>{k=k[0];var l=`constructor ${k.name}`;void 0===k.ea.pa&&(k.ea.pa=[]);if(void 0!==k.ea.pa[b-1])throw new N(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.ea.pa[b-1]=()=>
{Ub(`Cannot construct ${k.name} due to unbound types`,g)};Q([],g,m=>{m.splice(1,0,null);k.ea.pa[b-1]=$b(l,m,null,e,f);return[]});return[]})},g:(a,b,c,d,e,f,g,k,l)=>{var m=Vb(c,d);b=K(b);b=ac(b);f=V(e,f);Q([],[a],n=>{function x(){Ub(`Cannot call ${v} due to unbound types`,m)}n=n[0];var v=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&n.ea.Ja.push(b);var y=n.ea.ra,w=y[b];void 0===w||void 0===w.ja&&w.className!==n.name&&w.va===c-2?(x.va=c-2,x.className=n.name,y[b]=x):(Fb(y,b,v),y[b].ja[c-
2]=x);Q([],m,E=>{E=$b(v,E,n,f,g,l);void 0===y[b].ja?(E.va=c-2,y[b]=E):y[b].ja[c-2]=E;return[]});return[]})},R:a=>P(a,cc),s:(a,b,c,d)=>{function e(){}b=K(b);e.values={};P(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:(f,g)=>g.value,na:8,readValueFromPointer:dc(b,c,d),la:null});Gb(b,e)},k:(a,b,c)=>{var d=ec(a);b=K(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Eb(`${d.name}_${b}`,function(){})}});a.values[c]=
d;a[b]=d},p:(a,b,c)=>{b=K(b);P(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,na:8,readValueFromPointer:fc(b,c),la:null})},C:(a,b,c,d,e,f,g)=>{var k=Vb(b,c);a=K(a);a=ac(a);e=V(d,e);Gb(a,function(){Ub(`Cannot call ${a} due to unbound types`,k)},b-1);Q([],k,l=>{Qb(a,$b(a,[l[0],null].concat(l.slice(1)),null,e,f,g),b-1);return[]})},i:(a,b,c,d,e)=>{b=K(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var f=32-8*c;e=k=>k<<f>>>f}var g=b.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};
P(a,{name:b,fromWireType:e,toWireType:g,na:8,readValueFromPointer:ub(b,c,0!==d),la:null})},e:(a,b,c)=>{function d(f){var g=z()[f>>2];f=z()[f+4>>2];return new e(h().buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=K(c);P(a,{name:c,fromWireType:d,na:8,readValueFromPointer:d},{Ha:!0})},r:(a,b)=>{b=K(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(d){var e=z()[d>>2],f=d+4;if(c)for(var g=f,k=
0;k<=e;++k){var l=f+k;if(k==e||0==t()[l]){g=J(g,l-g);if(void 0===m)var m=g;else m+=String.fromCharCode(0),m+=g;g=l+1}}else{m=Array(e);for(k=0;k<e;++k)m[k]=String.fromCharCode(t()[f+k]);m=m.join("")}W(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new N("Cannot pass non-string to std::string");var g=c&&f?hc(e):e.length;var k=C(4+g+1),l=k+4;z()[k>>
2]=g;if(c&&f)g+=1,Y(e,t(),l,g);else if(f)for(f=0;f<g;++f){var m=e.charCodeAt(f);if(255<m)throw W(l),new N("String has UTF-16 code units that do not fit in 8 bits");t()[l+f]=m}else for(f=0;f<g;++f)t()[l+f]=e[f];null!==d&&d.push(W,k);return k},na:8,readValueFromPointer:Ob,la(d){W(d)}})},n:(a,b,c)=>{c=K(c);if(2===b){var d=jc;var e=kc;var f=lc;var g=k=>da()[k>>1]}else 4===b&&(d=mc,e=nc,f=oc,g=k=>z()[k>>2]);P(a,{name:c,fromWireType:k=>{for(var l=z()[k>>2],m,n=k+4,x=0;x<=l;++x){var v=k+4+x*b;if(x==l||0==
g(v))n=d(n,v-n),void 0===m?m=n:(m+=String.fromCharCode(0),m+=n),n=v+b}W(k);return m},toWireType:(k,l)=>{if("string"!=typeof l)throw new N(`Cannot pass non-string to C++ string type ${c}`);var m=f(l),n=C(4+m+b);z()[n>>2]=m/b;e(l,n+4,m+b);null!==k&&k.push(W,n);return n},na:8,readValueFromPointer:Ob,la(k){W(k)}})},T:(a,b)=>{b=K(b);P(a,{Qa:!0,name:b,na:0,fromWireType:()=>{},toWireType:()=>{}})},I:(a,b)=>{let c=pc[qc]=new Worker(rc);c.postMessage({$ww:qc,wasm:Ha,js:A.mainScriptUrlOrBlob||_scriptName,wasmMemory:p,
sb:a,sz:b});c.onmessage=Ua;return qc++},O:()=>1,v:()=>{kb=!1;uc=0},w:(a,b)=>{sc[a]&&(clearTimeout(sc[a].id),delete sc[a]);if(!b)return 0;var c=setTimeout(()=>{delete sc[a];wc(()=>Ic(a,xc()))},b);sc[a]={id:c,Va:b};return 0},K:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);z()[a>>2]=60*g;u()[b>>2]=Number(f!=e);b=k=>{var l=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%
60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(gc(a,c),gc(b,d)):(gc(a,d),gc(b,c))},E:(a,b)=>t().set(zc[a].Ea,b),B:()=>yc.length,D:()=>zc.length,z:(a,b)=>{a=yc[a].Pa;var c=hc(a)+1;Y(a,t(),b,c)},x:a=>zc[a].mode,F:a=>zc[a].Ea.length,A:(a,b)=>{a=yc[a].Sa;var c=hc(a)+1;Y(a,t(),b,c)},y:(a,b)=>{a=zc[a].Ta;var c=hc(a)+1;Y(a,t(),b,c)},H:()=>{a:{if(!Ac.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(hc(a)+
1);a=Y(a,b,0,b.length);b.length=a;Ac=b}b=Ac.shift()}return"number"===typeof b?b:-1},U:a=>{console.error(J(a))},W:a=>{console.log(J(a))},V:a=>{console.warn(J(a))},f:()=>Date.now(),l:a=>G(J(a)),m:xc,G:a=>Fa(J(a)),L:a=>{var b=t().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-p.buffer.byteLength+65535)/65536;try{p.grow(d);r();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
Q:(a,b,c,d)=>{pc[a].postMessage({_wsc:b,x:[c,d]})},h:(a,b,c,d,e)=>{pc[a].postMessage({_wsc:b,x:[c,d,e]})},M:(a,b)=>{var c=0;Dc().forEach((d,e)=>{var f=b+c;e=z()[a+4*e>>2]=f;for(f=0;f<d.length;++f)h()[e++]=d.charCodeAt(f);h()[e]=0;c+=d.length+1});return 0},N:(a,b)=>{var c=Dc();z()[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);z()[b>>2]=d;return 0},b:a=>{Ja=a;vc(a)},J:(a,b)=>{Fc(t().subarray(a,a+b));return 0},a:p,X:function(a,b,c){B[a].dispatchEvent(new CustomEvent(ta[b],{detail:0==c?null:J(c)}))},
u:vc},Z=function(){function a(c,d){Z=c.exports;ib=Z.$;Oa.unshift(Z.Y);Ha=d;H--;A.monitorRunDependencies?.(H);0==H&&(null!==Xa&&(clearInterval(Xa),Xa=null),I&&(c=I,I=null,c()));return Z}var b={a:Jc};H++;A.monitorRunDependencies?.(H);if(A.instantiateWasm)try{return A.instantiateWasm(b,a)}catch(c){G(`Module.instantiateWasm callback failed with error: ${c}`),na(c)}$a||=Za("Vosklet.wasm")?"Vosklet.wasm":A.locateFile?A.locateFile("Vosklet.wasm",D):D+"Vosklet.wasm";fb(b,function(c){a(c.instance,c.module)}).catch(na);
return{}}(),W=a=>(W=Z.Z)(a),C=A._malloc=a=>(C=A._malloc=Z._)(a),Sb=a=>(Sb=Z.aa)(a),Ic=(a,b)=>(Ic=Z.ba)(a,b),Ra=(a,b)=>(Ra=Z.ca)(a,b);A.UTF8ToString=J;var Kc;I=function Lc(){Kc||Mc();Kc||(I=Lc)};
function Mc(){function a(){if(!Kc&&(Kc=!0,A.calledRun=!0,!Ia)){Qa();ma(A);A.onRuntimeInitialized?.();if(A.postRun)for("function"==typeof A.postRun&&(A.postRun=[A.postRun]);A.postRun.length;){var b=A.postRun.shift();Pa.unshift(b)}Va(Pa)}}if(!(0<H))if(sa)ma(A),Qa();else{if(A.preRun)for("function"==typeof A.preRun&&(A.preRun=[A.preRun]);A.preRun.length;)Wa();Va(Na);0<H||(A.setStatus?(A.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>A.setStatus(""),1);a()},1)):a())}}
if(A.preInit)for("function"==typeof A.preInit&&(A.preInit=[A.preInit]);0<A.preInit.length;)A.preInit.pop()();Mc();moduleRtn=oa;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = loadVosklet;
else if (typeof define === 'function' && define['amd'])
  define([], () => loadVosklet);
